// react-redux/src/components/Profile/PreLoader.js
import React from 'react';
import { withStyles } from '@material-ui/core/styles';
import Paper from '@material-ui/core/Paper';
import Button from '@material-ui/core/Button';

const styles = {
  paper: {
    padding: 8,
    margin: '10px 0'
  },
  title: {
    color: '#cacaca',
    backgroundColor: '#cacaca',
    width: 150,
    margin: '0 0 5px 0'
  },
  email: {
    backgroundColor: '#cacaca',
    marginBottom: 10,
    width: 100,
    color: '#cacaca'
  },
  button: {
    width: '100%',
    textAlign: 'right'
  },
  buttonUnfollow: {
    borderColor: '#cacaca',
    backgroundColor: '#cacaca',
    color: '#cacaca'
  },
  stat: {
    backgroundColor: '#cacaca',
    color: '#cacaca',
    float: 'left',
    textAlign: 'center',
    fontSize: 20,
    fontWeight: 'bold',
    marginRight: 10
  },
  statTitle: {
    display: 'block',
    textTransform: 'uppercase',
    fontSize: 10,
    fontWeight: 'normal'
  }
};

const PreLoader = ({ classes }) => (
  <Paper className={classes.paper}>
    <h1 className={classes.title}>LOADING</h1>
    <div className={classes.email}>LOADING</div>
    <div className={classes.stat}>
      0<span className={classes.statTitle}>Posts</span>
    </div>
    <div className={classes.stat}>
      0<span className={classes.statTitle}>Following</span>
    </div>
    <div className={classes.stat}>
      0<span className={classes.statTitle}>Followers</span>
    </div>
    <div className={classes.button}>
      <Button className={classes.buttonUnfollow}>LOADING</Button>
    </div>
  </Paper>
);

export default withStyles(styles)(PreLoader);

// vue-vuex/src/components/Profile/PreLoader.vue
<template>
  <div>
    <h1 class="h1">LOADING</h1>
    <div class="email">LOADING</div>
    <div class="statBlock">
      <div class="stat">
        0
        <span class="statTitle">Posts</span>
      </div>
      <div class="stat">
        0
        <span class="statTitle">Following</span>
      </div>
      <div class="stat">
        0
        <span class="statTitle">Followers</span>
      </div>
      <div class="button">
        <v-btn flat color="#cacaca" class="button-unfollow">LOADING</v-btn>
      </div>
    </div>
  </div>
</template>

<style scoped>
.h1 {
  color: #cacaca;
  background-color: #cacaca;
  width: 150px;
  margin: 0 0 5px 0;
}
.email {
  background-color: #cacaca;
  margin-bottom: 10px;
  width: 100px;
  color: #cacaca;
}
.button {
  width: 100%;
  text-align: right;
}
.button-unfollow {
  border-color: #cacaca;
  background-color: #cacaca;
  color: #cacaca;
}
.stat {
  background-color: #cacaca;
  color: #cacaca;
  float: left;
  text-align: center;
  font-size: 20px;
  font-weight: bold;
  margin-right: 10px;
}
.statTitle {
  display: block;
  text-transform: uppercase;
  font-size: 10px;
  font-weight: normal;
}
</style>
