// react-redux/src/components/Home.js
import React, { Component } from 'react';
import { connect } from 'react-redux';
import List from './Posts/List';
import Login from './Auth/Login';

class Home extends Component {
  render() {
    const { auth } = this.props;
    return auth ? <List /> : <Login />;
  }
}

export default connect(state => ({
  auth: !!state.auth.isAuthenticated
}))(Home);

// vue-vuex/src/views/Home.vue
<template>
  <div>
    <div v-if="auth">
      <Start />
    </div>
    <div v-else>
      <Login />
    </div>
  </div>
</template>

<script>
import { mapState } from 'vuex';
import Start from './Start';
import Login from '@/components/Auth/Login.vue';

export default {
  name: 'home',
  components: {
    Login,
    Start
  },
  computed: {
    ...mapState({
      auth: state => state.auth.isAuthenticated
    })
  }
};
</script>
