// react-redux/src/components/Posts/Item.js
import React from 'react';
import { Link } from 'react-router-dom';
import Paper from '@material-ui/core/Paper';
import { withStyles } from '@material-ui/core/styles';
import calcTime from '../../utils/timeConverter';

const styles = {
  paper: {
    padding: 8,
    margin: '10px 0',
    display: 'flex'
  },
  avatar: {
    minWidth: 10,
    margin: '4px 10px 4px 4px',
    borderRadius: 3
  },
  login: {
    marginTop: 0,
    marginBottom: 5
  },
  time: {
    fontSize: 14,
    marginLeft: 10,
    fontWeight: 'normal',
    color: '#bbb'
  }
};

const Item = ({ post, classes }) => {
  return (
    <Paper className={classes.paper}>
      <div
        className={classes.avatar}
        style={{
          backgroundColor: `#${post.user.id.slice(post.user.id.length - 3)}`
        }}
      />
      <div>
        <h3 className={classes.login}>
          <Link to={`/profile/${post.user.id}`}>{post.user.login}</Link>
          <span className={classes.time}>{calcTime(post.createdAt)}</span>
        </h3>
        {post.text}
      </div>
    </Paper>
  );
};

export default withStyles(styles)(Item);

// vue-vuex/src/components/Posts/Item.vue
<template>
  <div class="item">
    <div class="avatar" :style="{backgroundColor: `#${post.user.id.slice(post.user.id.length - 3)}`}" />
    <div>
      <h3 class="login">
        <router-link :to="`/profile/${post.user.id}`">{{ post.user.login }}</router-link>
        <span class="time">{{ time }}</span>
      </h3>
      {{post.text}}
    </div>
  </div>
</template>

<script>
import calcTime from '@/utils/timeConverter.js';
export default {
  name: 'item',
  props: ['post'],
  computed: {
    time: function() {
      return calcTime(this.post.createdAt);
    }
  }
};
</script>

<style scoped>
.item {
  display: flex;
  text-align: left;
}
.avatar {
  min-width: 10px;
  margin: 4px 10px 4px 4px;
  border-radius: 3px;
}
.login {
  margin-top: 0;
  margin-bottom: 5px;
}
.time {
  font-size: 14px;
  margin-left: 10px;
  font-weight: normal;
  color: #bbb;
}
</style>
