// react-redux/src/components/Auth/Register.js
import React from 'react';
import PropTypes from 'prop-types';
import { withRouter } from 'react-router-dom';
import { connect } from 'react-redux';
import Paper from '@material-ui/core/Paper';
import { registerUser } from '../../actions/authActions';
import TextFieldGroup from '../Common/TextFieldGroup';
import Btn from '../Common/Btn';

const Register = ({ auth, history, errors, registerUser }) => {
  const [form, setValues] = React.useState({
    login: '',
    email: '',
    password: '',
    password2: ''
  });

  React.useEffect(() => {
    if (auth.isAuthenticated) history.push('/');
  }, [auth.isAuthenticated, errors, history]);

  const onChange = e => {
    setValues({ ...form, [e.target.name]: e.target.value });
  };

  const onSubmit = e => {
    e.preventDefault();
    registerUser(form, history);
  };

  return (
    <Paper style={{ padding: 20 }}>
      <form onSubmit={onSubmit}>
        <TextFieldGroup
          name="login"
          value={form.login}
          onChange={onChange}
          error={errors.login}
          label="Login"
        />
        <TextFieldGroup
          name="email"
          type="email"
          value={form.email}
          onChange={onChange}
          error={errors.email}
          label="Email"
        />
        <TextFieldGroup
          name="password"
          type="password"
          value={form.password}
          onChange={onChange}
          error={errors.password}
          label="Password"
        />
        <TextFieldGroup
          name="password2"
          type="password"
          value={form.password2}
          onChange={onChange}
          error={errors.password2}
          label="Repeat password"
        />
        <Btn variant="outlined" type="submit" value="Submit" />
      </form>
    </Paper>
  );
};

Register.propTypes = {
  registerUser: PropTypes.func.isRequired,
  auth: PropTypes.object.isRequired,
  errors: PropTypes.object.isRequired
};

const mapStateToProps = state => ({
  auth: state.auth,
  errors: state.errors
});

export default connect(
  mapStateToProps,
  { registerUser }
)(withRouter(Register));

// vue-vuex/src/components/Auth/Register.vue
<template>
  <v-card class="paper">
    <form v-on:submit.prevent="onSubmit">
      <v-text-field color="teal lighten-1" type="text" label="Login" v-model="login" :error="errors && errors.login" :error-messages="errors && errors.login" />
      <v-text-field color="teal lighten-1" type="email" label="Email" v-model="email" :error="errors && errors.email" :error-messages="errors && errors.email" />
      <v-text-field color="teal lighten-1" type="password" label="Password" v-model="password" :error="errors && errors.password" :error-messages="errors && errors.password" />
      <v-text-field color="teal lighten-1" type="password" label="Repeat password" v-model="password2" :error="errors && errors.password2" :error-messages="errors && errors.password2" />

      <v-btn type="submit" color="teal lighten-1" depressed dark>
        Register
      </v-btn>
    </form>
  </v-card>
</template>

<script>
import { mapState } from 'vuex';
import { REGISTER } from '@/store/actions.type';

export default {
  name: 'register',
  data() {
    return {
      login: '',
      email: '',
      password: '',
      password2: ''
    };
  },
  computed: {
    ...mapState({
      errors: state => state.auth.errors,
      auth: state => state.auth.isAuthenticated
    })
  },
  created() {
    if (this.auth) this.$router.push({ name: 'home' });
  },
  methods: {
    onSubmit() {
      const newUser = {
        login: this.login,
        email: this.email,
        password: this.password,
        password2: this.password2
      };
      this.$store.dispatch(REGISTER, newUser);
    }
  }
};
</script>
